### ISSUE TITLE
Open files not show supported files

### ISSUE THREAD

**Issue by acateon** [Rasbats/photolayer_pi#7]
Opening browse for files does not show supported GeoTIFFs (*.tiff). Instead one have to select show all to be able to select a file.

This should also support batch import of layers instead of picking one after another.

**Comment by Rasbats** [comment]
Can you give an example of a use case where several geotiffs of the same area need to be open at the same time and not selected individually? Thanks.

**Comment by Rasbats** [comment]
Browse for files can be fixed easily. TODO.

**Comment by acateon** [comment]
> Can you give an example of a use case where several geotiffs of the same area need to be open at the same time and not selected individually? Thanks.

In my case i would prefer to have all my "chart specials" loaded at the same time for planning etc. For example if i got a handfull specials over anchorages and i would like to easy go between them.

In regards to this, the plugin should remember added tiffs which it doesent do now. Perhaps this has something to do with it not recognizing tiffs as supported files as of now.

**Comment by Rasbats** [comment]
You may be right but .tif files are saved. Are you using v2.1.1?
[https://github.com/Rasbats/photolayer_pi/releases/tag/v2.1.1](url)

**Comment by acateon** [comment]
I'm using 2.-1717986919 as it says on the about page.

**Comment by Rasbats** [comment]
Now updated:
[https://github.com/Rasbats/photolayer_pi/releases/tag/v2.1.2](url)

**Comment by Rasbats** [comment]
'tif' and 'tiff' etc both recognised.
